### ISSUE TITLE
question about design compiler target library 

### ISSUE THREAD

**Issue by Arieswithme** [nimish15shah/DAG_Processor#2]
I was wondering if it is possible for you to provide me with information regarding the specific DC target library you use in the corresponding paper.

**Comment by nimish15shah** [comment]
Hi, the design was synthesized with TSMC's proprietary library, and I used Cadence's genus tool.

**Comment by Arieswithme** [comment]
> Hi, the design was synthesized with TSMC's proprietary library, and I used Cadence's genus tool.

Thank you very much for your reply! Would it be possible to show the details of the TSMC target library used in the paper DPU-V2 (such as threshold voltage, temperature, power supply voltage), thank you for your patience.

**Comment by nimish15shah** [comment]
Sorry, I can't share that.

**Comment by Arieswithme** [comment]
Understood, no problem. Thanks anyway!

**Comment by Arieswithme** [comment]
Hello, one more question, have you ever deployed the DPU-v2 in FPGAs? Recently I was trying FPGA implementation but had some route problems and was wondering if you have any experience with this, thanks again for your time and patience!

**Comment by nimish15shah** [comment]
No, haven't tried an FPGA implementation.

**Comment by Arieswithme** [comment]
Thank you very much for your reply!
